spring:  
  profiles:
    active: dev
  datasource:  # 数据库配置
    type: com.alibaba.druid.pool.DruidDataSource # 使用阿里的druid数据源
    driver-class-name: com.mysql.jdbc.Driver    # oracle.jdbc.driver.OracleDriver
pagehelper:
  helperDialect: oracle
  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
#  redis: 
#    database: 0 # Redis数据库索引（默认为0）
#    host: 127.0.0.1 # Redis服务器地址
#    port: 6379 # Redis服务器连接端口
#    timeout: 0 # 连接超时时间（毫秒）
#    jedis: 
#      pool: 
#        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 8 # 连接池中的最大空闲连接
#        min-idle: 0 # 连接池中的最小空闲连接
mybatis: # 配置mybatis
  type-aliases-package: com.ny.model
  mapper-locations: classpath:mapper/*.xml 
logging: 
  config: "classpath:logback.xml"  # 配置日志
  level: 
    org: 
      springframework: 
        web: ERROR 

redis:  # 系统参数配置
  key:
    user-resources: api_user_resources_  # redis key = user_resources
    
jwt: 
  header: Authorization 
  secret: mySecret
  expiration: 604800

druid:
  loginUsername:  druid
  loginPassword:  wokeji123456
